<div style="
background:#0b1220;              
padding:35px;
border:3px solid #334155;        
border-radius:15px;
margin:20px 0;
">

<h1 style="
font-size:35px;
color:#3b82f6;                  
text-align:center;
margin-top:0;
margin-bottom:10px;
">
Caso de Negocio 2
</h1>

<h2 style="
font-size:25px;
color:#e5e7eb;                   
text-align:center;
font-weight:normal;
margin-top:0;
margin-bottom:25px;
">
Análisis Exploratorio de los Factores Asociados a la Mora Crediticia
</h2>

<hr style="border:1px solid #334155; margin-bottom:30px;"> 

<h3 style="
font-size:20px;
color:#3b82f6;                  
margin-bottom:10px;
">
Contexto del negocio
</h3>

<p style="
font-size:17px;
color:#e5e7eb;                  
line-height:1.8;
text-align:justify;
">
Banco Capital GT busca comprender las características de los clientes que solicitan créditos y evaluar los factores asociados al incumplimiento de pago (mora). La gerencia de riesgos desea identificar patrones en variables demográficas, laborales y financieras que permitan mejorar la evaluación crediticia y fortalecer la gestión del riesgo.
</p>

<h3 style="
font-size:20px;
color:#3b82f6;               
margin-top:35px;
margin-bottom:10px;
">
Objetivo general
</h3>

<p style="
font-size:17px;
color:#e5e7eb;                 
line-height:1.8;
text-align:justify;
">
Analizar las características financieras y demográficas de los clientes con créditos activos para identificar patrones asociados al comportamiento de pago y generar información que apoye la toma de decisiones en la gestión del riesgo crediticio.
</p>

</div>

<div style="
background:#0b1220;
padding:30px;
border:3px solid #334155;
border-radius:15px;
margin:20px 0;
">

<h2 style="
font-size:35px;
color:#3b82f6;
text-align:center;
margin-top:0;
margin-bottom:30px;
">
Preguntas de negocio
</h2>

<ol style="
font-size:17px;
color:#e5e7eb;
line-height:2;
padding-left:25px;
">

<li><b>¿Cuál es la distribución de clientes con y sin mora?</b></li>

<li><b>¿Qué sectores laborales presentan una mayor proporción de clientes en mora?</b></li>

<li><b>¿Existe relación entre el ingreso mensual y el monto del préstamo otorgado?</b></li>

<li><b>¿Cómo varía la antigüedad laboral entre clientes con y sin mora?</b></li>

<li><b>¿Qué grupos de edad presentan una mayor concentración de clientes en mora?</b></li>

</ol>

</div>

In [2]:
#Librerias
from math import pi
import numpy as np
import pandas as pd
from bokeh.io import output_notebook
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, RangeTool, HoverTool, NumeralTickFormatter, GlobalInlineStyleSheet, DatetimeTickFormatter, CustomJS, Legend, LegendItem, Label, TapTool
from bokeh.layouts import column
from bokeh.transform import factor_cmap, dodge
from IPython.display import display, HTML

In [3]:
#base de datos
df = pd.read_csv("caso_2_lim.csv")
df

,cliente_id,edad,ingreso,prestamo,cuota,sector,antiguedad_laboral,mora
0,1,35,19118.0,185313.0,3496.47,Comercio,3,No
1,2,43,12083.0,134250.0,8390.62,Gobierno,18,No
2,3,63,17289.0,72609.0,1396.33,Gobierno,22,No
3,4,56,6918.0,102832.0,2337.09,Comercio,27,No
4,5,23,11504.0,47689.0,973.24,Servicios,10,No
...,...,...,...,...,...,...,...,...
995,996,27,14381.0,79656.0,3620.73,Industria,8,No
996,997,30,18946.0,120059.0,4617.65,Industria,30,No
997,998,26,11500.0,163903.0,2731.72,Servicios,21,No
998,999,33,12130.0,41963.0,2331.28,Servicios,0,No
999,1000,54,22608.0,15418.0,223.45,Servicios,0,No

In [4]:
#Tema
output_notebook()

THEMES = {
    "midnight_blue": {
        "BACKGROUND": "#0b1220",
        "PANEL": "#111827",
        "CARD": "#1e293b",
        "BORDER": "#334155",
        "GRID": "#0b1220",
        "TEXT": "#e5e7eb",
        "TEXT_SOFT": "#94a3b8",
        "ACCENT": "#3b82f6",   
        "POSITIVE": "#10b981",
        "NEGATIVE": "#f97316",
        "WARNING": "#f59e0b",   
        "NEUTRAL": "#64748b", 
        "TEXT_SIZE": "10pt",
        "GRID_ALPHA":0.35
        
    }
}
theme = THEMES["midnight_blue"]

<div style="
background:#0b1220;
padding:30px;
border:3px solid #334155;
border-radius:15px;
margin:20px 0;
">

<h2 style="
font-size:35px;
color:#d4af37;
text-align:left;
margin-left:25px;
margin-bottom:30px;
">
Pregunta 1
</h2>

<ol style="
font-size:25px;
color:#e5e7eb;
line-height:1.5;
padding-left:25px;
">
<b>¿Cuál es la distribución de clientes con y sin mora?</b>
</ol>

</div>

In [5]:
#Datos pregunta 1
df_ques1 = (df.groupby("mora").size().reset_index(name = "clientes"))
df_ques1["porcentaje"] = (df_ques1["clientes"]/df_ques1["clientes"].sum())
df_ques1["angulo"] = (df_ques1["porcentaje"] * 2 * pi)
df_ques1["end_angle"] = df_ques1["angulo"].cumsum()
df_ques1["start_angle"] = (df_ques1["end_angle"] - df_ques1["angulo"])
colors = {"Sí": theme["NEGATIVE"],"No": theme["POSITIVE"]}
df_ques1["colors"] = df_ques1["mora"].map(colors)
df_ques1["porcentaje_str"] = (df_ques1["porcentaje"] * 100).round(2)
source = ColumnDataSource(df_ques1)

df_ques1.columns.name = None
df_ques1

,mora,clientes,porcentaje,angulo,end_angle,start_angle,colors,porcentaje_str
0,No,873,0.873,5.485221,5.485221,0.000000,#10b981,87.3
1,Sí,127,0.127,0.797965,6.283185,5.485221,#f97316,12.7

In [38]:
# Gráfica pregunta 1
p = figure(
    width=650,
    height=500,
    x_range=(-1, 1),
    y_range=(-1, 1),
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    tools="hover, save",
    tooltips="""
    <div style="
        background:#111827;
        border:1px solid #3b82f6;
        border-radius:8px;
        padding:8px;
        color:white;
    ">
        <b>Estado:</b> @mora <br>
        <b>Clientes:</b> @clientes{0,0} <br>
        <b>Porcentaje:</b> @porcentaje_str %
    </div>
    """
)

p.annular_wedge(
    x=0,
    y=0,
    inner_radius=0.35,
    outer_radius=0.60,
    start_angle="start_angle",
    end_angle="end_angle",
    color="colors",
    legend_field="mora",
    line_color=theme["BACKGROUND"],
    line_width=3,
    source=source
)

texto = Label(
    x=0,
    y=0.05,
    x_units="data",
    y_units="data",
    text="Tasa de Mora",
    text_align="center",
    text_baseline="middle",
    text_color=theme["TEXT_SOFT"],
    text_font_size="13pt"
)

valor = Label(
    x=0,
    y=-0.1,
    x_units="data",
    y_units="data",
    text=f"{df_ques1.loc[df_ques1['mora']=='Sí','porcentaje_str'].iloc[0]}%",
    text_align="center",
    text_baseline="middle",
    text_font_size="20pt",
    text_font_style="bold",
    text_color=theme["ACCENT"]
)


p.stylesheets = [
    GlobalInlineStyleSheet(css="""
    .bk-Tooltip {
        --tooltip-color: transparent !important;
        --tooltip-border: transparent !important;
    }

    .bk-tooltip-content {
        background: transparent !important;
        border: none !important;
        box-shadow: none !important;
        padding: 0 !important;
    }
    """)
]

p.title.text = "Distribución de Clientes según Mora"
p.title.text_color = theme["ACCENT"]
p.title.text_font_size = "15pt"
p.title.align = "center"
p.legend.location = "right"
p.legend.label_text_color = theme["TEXT"]
p.legend.background_fill_color = theme["PANEL"]
p.legend.border_line_color = theme["BORDER"]
p.legend.label_text_font_size = "11pt"
p.add_layout(texto)
p.add_layout(valor)
p.axis.visible = False
p.grid.visible = False
p.outline_line_color = theme["BORDER"]
p.toolbar.logo = None
p.toolbar.autohide = True

show(p)

<div style="
background:#0b1220;
padding:25px;
border-left:6px solid #3b82f6;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<h3 style="
font-size:28px;
color:#3b82f6;
margin-top:0;
">
Análisis
</h3>
<p style="
font-size:18px;
color:#e0e0e0 !important;
line-height:1.8;
text-align:justify;
">

El análisis de la cartera de crédito muestra que, de un total de 1,000 clientes, 127 presentan incumplimiento en sus obligaciones de pago, lo que representa una tasa de mora del <b>12.7%</b>. En contraste, el <b>87.3%</b> de los clientes mantiene un comportamiento de pago al día, reflejando que la mayor parte de la cartera no presenta atrasos.

</p>

<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

Aunque la mayoría de los clientes cumple con sus obligaciones financieras, una tasa de mora del <b>12.7%</b> constituye un indicador relevante que debe evaluarse en función de las políticas internas de riesgo y de los objetivos establecidos por la institución financiera. Su interpretación dependerá del nivel máximo de mora considerado aceptable por el banco.

</p>

<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

Desde una perspectiva de gestión del riesgo, resulta recomendable profundizar el análisis para identificar las características asociadas a los clientes en situación de mora, considerando variables como el nivel de ingresos, el monto del préstamo, la antigüedad laboral, el sector económico y la edad. Este tipo de análisis permitirá diseñar estrategias de prevención, fortalecer los procesos de otorgamiento de crédito y reducir el riesgo de incumplimiento en el futuro.

</p>

</div>

<div style="
background:#0b1220;
padding:30px;
border:3px solid #334155;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#e5e7eb;
line-height:1.5;
padding-left:25px;
">
<b>Pregunta 2</b>
    
<b>¿Qué sectores laborales presentan una mayor proporción de clientes en mora?</b>
</ol>

</div>

In [6]:
#Datos pregunta 2
df_ques2 = (df.groupby(["sector","mora"]).size().unstack().reset_index())
source = ColumnDataSource(df_ques2)
df_ques2.columns.name = None
df_ques2

      sector   No  Sí
0   Comercio  242  42
1   Gobierno  217  31
2  Industria  205  25
3  Servicios  209  29

In [7]:
#Gráfica pregunta 2
p = figure(
    x_range=df_ques2["sector"].tolist(),
    width=750,
    height=500
)
p.vbar(
    x=dodge("sector", -0.15, range=p.x_range),
    top="No",
    width=0.25,
    source=source,
    color=theme["POSITIVE"],
    legend_label="Sin Mora"
)

p.vbar(
    x=dodge("sector", 0.15, range=p.x_range),
    top="Sí",
    width=0.25,
    source=source,
    color=theme["NEGATIVE"],
    legend_label="Con Mora"
)

hover = HoverTool(
    tooltips=f"""
    <div style="
        background:{theme['PANEL']};
        border:1px solid {theme['ACCENT']};
        border-radius:8px;
        padding:8px;
        color:{theme['TEXT']};
    ">

        <b>Sector:</b> @sector <br>
        <b>Sin Mora:</b> @{{No}}{{0,0}} <br>
        <b>Con Mora:</b> @{{Sí}}{{0,0}}

    </div>
    """
)

p.title.text = "Clientes con y sin Mora por Sector Económico"
p.title.text_color = theme["ACCENT"]
p.title.text_font_size = "15pt"
p.title.align = "center"
p.xaxis.axis_label = "Sector Económico"
p.yaxis.axis_label = "Número de Clientes"
p.xaxis.axis_label_text_color = theme["TEXT"]
p.yaxis.axis_label_text_color = theme["TEXT"]
p.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p.xaxis.major_label_text_font_size = "11pt"
p.yaxis.major_label_text_font_size = "11pt"
p.yaxis.formatter = NumeralTickFormatter(format="0,0")
p.xgrid.grid_line_color = None
p.ygrid.grid_line_color = theme["GRID"]
p.ygrid.grid_line_alpha = 0.30
p.outline_line_color = theme["BORDER"]
p.legend.location = "top_right"
p.legend.orientation = "vertical"
p.legend.background_fill_color = theme["PANEL"]
p.legend.border_line_color = theme["BORDER"]
p.legend.label_text_color = theme["TEXT"]
p.legend.label_text_font_size = "11pt"
p.legend.click_policy = "hide"
p.add_tools(hover)
p.toolbar.logo = None
p.toolbar.autohide = True
p.background_fill_color = theme["BACKGROUND"]
p.border_fill_color = theme["PANEL"]

show(p)

<div style="
background:#0b1220;
padding:25px;
border-left:6px solid #3b82f6;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;
">

<h3 style="
font-size:28px;
color:#3b82f6;
margin-top:0;
">
Análisis
</h3>
<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

La distribución de clientes en mora por sector económico muestra diferencias moderadas entre las categorías analizadas. El sector Comercio registra la mayor cantidad de clientes en mora con <b>42 casos</b>, mientras que Industria presenta la menor con <b>25 casos</b>, lo que representa una diferencia de <b>17 clientes</b> entre ambos extremos. En términos generales, las variaciones observadas son relativamente reducidas considerando el tamaño de la cartera total.

</p>

<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

Asimismo, los sectores que concentran un mayor número de clientes también presentan una mayor cantidad absoluta de casos de mora. Este comportamiento sugiere que las diferencias observadas podrían estar asociadas al tamaño de la cartera de clientes en cada sector más que a un efecto propio de la actividad económica. No obstante, con esta visualización no es posible establecer una relación causal o afirmar que el sector económico sea un factor determinante del incumplimiento.

</p>

<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

Como resultado, las estrategias de gestión del riesgo crediticio no deberían diseñarse únicamente en función del sector económico. Se recomienda complementar el análisis incorporando variables con mayor capacidad explicativa, como la relación cuota-ingreso, el monto del préstamo, la antigüedad laboral o el historial crediticio, con el fin de identificar los factores que influyen de manera más significativa en la probabilidad de mora.

</p>

</div>

<div style="
background:#0b1220;
padding:30px;
border:3px solid #334155;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#e5e7eb;
line-height:1.5;
padding-left:25px;
">
<b>Pregunta 3</b>
        
<b>¿Existe relación entre el ingreso mensual y el monto del préstamo otorgado?</b>
</ol>

</div>

In [19]:
#Datos pregunta 3
df_ques3 = df[["ingreso","prestamo","sector"]]
source = ColumnDataSource(df_ques3)

df_ques3

     ingreso  prestamo     sector
0    19118.0  185313.0   Comercio
1    12083.0  134250.0   Gobierno
2    17289.0   72609.0   Gobierno
3     6918.0  102832.0   Comercio
4    11504.0   47689.0  Servicios
..       ...       ...        ...
995  14381.0   79656.0  Industria
996  18946.0  120059.0  Industria
997  11500.0  163903.0  Servicios
998  12130.0   41963.0  Servicios
999  22608.0   15418.0  Servicios

[1000 rows x 3 columns]

In [20]:
#Gráfica pregunta 3
p = figure(
    height=400, width=800,
    tools="pan,wheel_zoom,reset,save,tap",
    x_axis_label="Ingreso (Q)",
    y_axis_label="Saldo disponible (Q)",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    title="Relación ingreso - prestamo"
)

renderer = p.scatter(
    x="ingreso", y="prestamo",
    source=source,
    size=8,
    fill_color=factor_cmap("sector", palette=["#d4af37","#29a57a","#377ad4","#f59e0b"], factors=df["sector"].unique()),
    line_color=None
)

hover = HoverTool(tooltips="""
    <div style="background:#0b0b0b; border:1px solid #d4af37; border-radius:6px; padding:6px; color:#fff;">
        <div><b>Cliente:</b> @cliente_id</div>
        <div><b>Ingreso:</b> @ingreso{0,0}</div>
        <div><b>Prestamo:</b> @prestamo{0,0}</div>
        <div><b>Sector:</b> @sector</div>
    </div>
""", renderers=[renderer])
p.add_tools(hover)

callback = CustomJS(args=dict(source=source), code="""
    const indices = source.selected.indices;
    if (indices.length > 0) {
        const seg = source.data['sector'][indices[0]];
        const new_indices = [];
        for (let i = 0; i < source.data['sector'].length; i++) {
            if (source.data['sector'][i] === seg) {
                new_indices.push(i);
            }
        }
        source.selected.indices = new_indices;
    }
""")

taptool = p.select(type=TapTool)
taptool.callback = callback
p.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p.title.text_color = theme["ACCENT"] 
p.title.text_font_size = "20pt"        
p.title.align = "center"  
p.xaxis.axis_label_text_color = theme["TEXT"]
p.yaxis.axis_label_text_color = theme["TEXT"]
p.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p.outline_line_color = theme["BORDER"]
p.xgrid.grid_line_color = theme["GRID"]
p.ygrid.grid_line_color = theme["GRID"]
p.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p.ygrid.grid_line_alpha = theme["GRID_ALPHA"]

p.toolbar.logo = None
p.toolbar.autohide = True
show(p)

<div style="
background:#0b1220;
padding:25px;
border-left:6px solid #3b82f6;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;
">

<h3 style="
font-size:28px;
color:#3b82f6;
margin-top:0;
">
Análisis
</h3>
<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

El análisis de dispersión entre el ingreso mensual de los clientes y el monto del préstamo no evidencia un patrón o tendencia claramente definida. Los datos se encuentran distribuidos de forma heterogénea a lo largo del gráfico, sin observarse una relación lineal aparente que permita concluir que un mayor nivel de ingresos esté asociado sistemáticamente con préstamos de mayor o menor cuantía. De igual forma, la distribución por sector económico tampoco muestra diferencias visuales que permitan identificar un comportamiento distintivo entre los distintos grupos analizados.

</p>

<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

Con base en el análisis exploratorio realizado, la relación entre ingreso, monto del préstamo y sector económico no proporciona evidencia suficiente para considerarse un factor explicativo del comportamiento de la cartera crediticia. En consecuencia, estos resultados no permiten orientar estrategias de gestión del riesgo crediticio sustentadas únicamente en dichas variables, siendo necesario complementar el estudio con análisis estadísticos y variables adicionales que permitan identificar los factores con mayor capacidad explicativa.

</p>

<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

Por lo anterior, las políticas de evaluación y administración del riesgo crediticio deberían continuar considerando un enfoque integral que incorpore múltiples variables, tales como el historial de pago, la antigüedad laboral, el nivel de endeudamiento, la capacidad de pago y otros indicadores financieros. La incorporación de estos factores permitirá construir modelos de riesgo más robustos y mejorar la identificación de los principales determinantes de la mora.

</p>

</div>

<div style="
background:#0b1220;
padding:30px;
border:3px solid #334155;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#e5e7eb;
line-height:1.5;
padding-left:25px;
">
<b>Pregunta 4</b>
    
<b>¿Cómo varía la antigüedad laboral entre clientes con y sin mora?</b>
</ol>

</div>

In [22]:
#Datos pregunta 4
df_ques4 = df[["antiguedad_laboral","mora"]]
source = ColumnDataSource(df_ques4)
df_ques4.columns.name = None
df_ques4

     antiguedad_laboral mora
0                     3   No
1                    18   No
2                    22   No
3                    27   No
4                    10   No
..                  ...  ...
995                   8   No
996                  30   No
997                  21   No
998                   0   No
999                   0   No

[1000 rows x 2 columns]

In [21]:
#Gráfica pregunta 4
cats = ["Sin mora", "Con mora"]

vals = [
    df[df["mora"] == "No"]["antiguedad_laboral"],
    df[df["mora"] == "Sí"]["antiguedad_laboral"]
]

p_box = figure(
    x_range=cats,
    title="Distribución de la Antigüedad Laboral según Estado de Mora",
    width=750,
    height=450,
    tools="pan,wheel_zoom,box_zoom,reset,save"
)

estadisticas = []

for i, v in enumerate(vals):
    q1 = v.quantile(0.25)
    q2 = v.median()
    q3 = v.quantile(0.75)
    mean_val = v.mean()
    iqr = q3 - q1
    upper = v[v <= q3 + 1.5 * iqr].max()
    lower = v[v >= q1 - 1.5 * iqr].min()
    outliers = v[(v > upper) | (v < lower)]
    cat = cats[i]
    color = theme["POSITIVE"] if i == 0 else theme["NEGATIVE"]
    estadisticas.append({
        "estado": cat,
        "media": mean_val,
        "mediana": q2,
        "q1": q1,
        "q3": q3,
        "min": lower,
        "max": upper
    })

    p_box.vbar(
        x=[cat],
        width=0.45,
        bottom=[q1],
        top=[q3],
        fill_color=color,
        line_color="black",
        alpha=0.75
    )

    p_box.rect(
        x=[cat],
        y=[q2],
        width=0.6,
        height=0.03,
        color="black"
    )

    p_box.scatter(
        x=[cat],
        y=[mean_val],
        marker="diamond",
        size=12,
        color="#f59e0b"
    )

    p_box.segment(
        x0=[cat],
        y0=[q3],
        x1=[cat],
        y1=[upper],
        line_width=2,
        line_color="#475569"
    )

    p_box.segment(
        x0=[cat],
        y0=[q1],
        x1=[cat],
        y1=[lower],
        line_width=2,
        line_color="#475569"
    )

    p_box.rect(
        x=[cat],
        y=[upper],
        width=0.18,
        height=0.01,
        color="#475569"
    )

    p_box.rect(
        x=[cat],
        y=[lower],
        width=0.18,
        height=0.01,
        color="#475569"
    )

    if len(outliers) > 0:
        p_box.scatter(
            x=[cat] * len(outliers),
            y=outliers.tolist(),
            size=6,
            color="#f59e0b",
            alpha=0.7
        )

p_box.toolbar.logo = None

stats_source = ColumnDataSource(pd.DataFrame(estadisticas))

hover_renderer = p_box.scatter(
        x="estado",
        y="media",
        size=40,
        alpha=0,
        source=stats_source
)

hover = HoverTool(
    renderers=[hover_renderer],
    tooltips="""
    <div style="
        background:#111827;
        border:1px solid #3b82f6;
        border-radius:8px;
        padding:10px;
        color:white;
    ">
        <b>Estado:</b> @estado<br><br>

        <b>Media:</b> @media{0.0} años<br>
        <b>Mediana:</b> @mediana{0.0} años<br>
        <b>Q1:</b> @q1{0.0} años<br>
        <b>Q3:</b> @q3{0.0} años<br>
        <b>Mínimo:</b> @min{0} años<br>
        <b>Máximo:</b> @max{0} años
    </div>
    """
)

p_box.add_tools(hover)
p_box.background_fill_color = theme["BACKGROUND"]
p_box.border_fill_color = theme["PANEL"]
p_box.outline_line_color = theme["BORDER"]
p_box.title.text_color = theme["ACCENT"]
p_box.title.text_font_size = "15pt"
p_box.title.align = "center"
p_box.yaxis.axis_label = "Antigüedad Laboral (años)"
p_box.xaxis.axis_label_text_color = theme["TEXT"]
p_box.yaxis.axis_label_text_color = theme["TEXT"]
p_box.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_box.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_box.xaxis.axis_line_color = theme["BORDER"]
p_box.yaxis.axis_line_color = theme["BORDER"]
p_box.xaxis.major_tick_line_color = theme["TEXT_SOFT"]
p_box.yaxis.major_tick_line_color = theme["TEXT_SOFT"]
p_box.xaxis.minor_tick_line_color = None
p_box.yaxis.minor_tick_line_color = None
p_box.xgrid.grid_line_color = None
p_box.ygrid.grid_line_color = theme["GRID"]
p_box.ygrid.grid_line_alpha = 0.35
p_box.toolbar.logo = None
p_box.toolbar.autohide = True
p_box.y_range.start = -1
p_box.y_range.end = df["antiguedad_laboral"].max() + 2


p_box.stylesheets = [
    GlobalInlineStyleSheet(css="""
    .bk-Tooltip{
        --tooltip-color:transparent !important;
        --tooltip-border:transparent !important;
    }

    .bk-tooltip-content{
        background:transparent !important;
        border:none !important;
        box-shadow:none !important;
        padding:0 !important;
    }
    """)
]

show(p_box)

<div style="
background:#0b1220;
padding:25px;
border-left:6px solid #3b82f6;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;
">

<h3 style="
font-size:28px;
color:#3b82f6;
margin-top:0;
">
Análisis
</h3>


<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

La distribución de la antigüedad laboral entre los clientes con y sin mora presenta un comportamiento muy similar. Ambos grupos muestran valores mínimos y máximos comparables, así como una dispersión semejante. La principal diferencia se observa en la concentración de los datos, donde los clientes con mora presentan una mayor densidad de observaciones aproximadamente entre los <b>6.5 y 22 años</b> de antigüedad laboral. Sin embargo, esta diferencia resulta poco pronunciada y no permite identificar un patrón claramente diferenciador entre ambos grupos.

</p>

<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

A partir de este análisis descriptivo, la antigüedad laboral por sí sola no parece constituir un factor suficientemente explicativo del comportamiento de la mora. En consecuencia, se recomienda complementar este estudio incorporando variables adicionales, como el nivel de ingresos, el monto del préstamo, la relación cuota-ingreso y otras características del cliente, así como aplicar técnicas estadísticas o modelos predictivos que permitan evaluar la influencia conjunta de estos factores sobre el riesgo crediticio.

</p>


</div>

<div style="
background:#0b1220;
padding:30px;
border:3px solid #334155;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#e5e7eb;
line-height:1.5;
padding-left:25px;
">
<b>Pregunta 5</b>
    
<b>¿Qué grupos de edad presentan una mayor concentración de clientes en mora?</b>
</ol>

</div>

In [58]:
#Datos pregunta 5
df_ques5 = df[["cliente_id","edad","mora"]].copy()
df_ques5["mora_bin"] = (df_ques5["mora"] == "Sí").astype(int)
bins = list(range(0, 105, 5))
labels = [f"{i}-{i+4}" for i in bins[:-1]]
df_ques5["grupo_edad"] = pd.cut(df["edad"], bins=bins, labels=labels, right=False)
df_ques5 = (df_ques5.groupby("grupo_edad", observed=False).agg(clientes=("cliente_id","count"), clientes_mora=("mora_bin","sum")).reset_index())
df_ques5["porcentaje_mora"] = ( df_ques5["clientes_mora"] / df_ques5["clientes"] * 100).round(2)
source = ColumnDataSource(df_ques5)
df_ques5.columns.name = None
df_ques5

   grupo_edad  clientes  clientes_mora  porcentaje_mora
0         0-4         0              0              NaN
1         5-9         0              0              NaN
2       10-14         0              0              NaN
3       15-19         0              0              NaN
4       20-24       108             15            13.89
5       25-29       123             12             9.76
6       30-34        96             13            13.54
7       35-39       114             12            10.53
8       40-44       106             15            14.15
9       45-49       109             14            12.84
10      50-54        96             11            11.46
11      55-59        95             14            14.74
12      60-64       123             19            15.45
13      65-69        30              2             6.67
14      70-74         0              0              NaN
15      75-79         0              0              NaN
16      80-84         0              0              NaN
17      85-89         0              0              NaN
18      90-94         0              0              NaN
19      95-99         0              0              NaN

In [57]:
#Gráfica pregunta 5

p = figure(
    x_range=list(df_ques5["grupo_edad"]),
    height=350, width=750,
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    tools="pan,wheel_zoom,reset,save",
    title="Distribución de mora por edad"
)

p.vbar(
    x="grupo_edad",
    top="porcentaje_mora", 
    width=0.75,
    source=source,
    fill_color=theme["ACCENT"], 
    line_color=theme["BORDER"]
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#111827;
        border:1px solid #3b82f6;
        border-radius:8px;
        padding:8px;
        color:white;
    ">
        <b>Grupo de edad:</b> @grupo_edad <br>
        <b>Clientes:</b> @clientes <br>
        <b>Clientes con mora:</b> @clientes_mora <br>
        <b>Tasa de mora:</b> @porcentaje_mora{0.0}% 
    </div>
    """
)

p.add_tools(hover)

p.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p.xaxis.major_label_orientation = 1.0  
p.title.text_color = theme["ACCENT"] 
p.title.text_font_size = "20pt"        
p.title.align = "center"  
p.xaxis.axis_label_text_color = theme["TEXT"]
p.yaxis.axis_label_text_color = theme["TEXT"]
p.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p.outline_line_color = theme["BORDER"]
p.xgrid.grid_line_color = theme["GRID"]
p.ygrid.grid_line_color = theme["GRID"]
p.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p.ygrid.grid_line_alpha = theme["GRID_ALPHA"]

p.toolbar.logo = None
p.toolbar.autohide = True

show(p)

<div style="
background:#0b1220;
padding:25px;
border-left:6px solid #3b82f6;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;
">

<h3 style="
font-size:28px;
color:#3b82f6;
margin-top:0;
">
Análisis
</h3>

<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

La distribución de clientes en mora por grupo de edad muestra que la mayor concentración se encuentra en los rangos comprendidos entre <b>20 y 64 años</b>. En estos grupos, la cantidad de clientes con incumplimiento oscila aproximadamente entre <b>12 y 19 clientes</b>, lo que evidencia una distribución relativamente homogénea a lo largo de la mayor parte de la población analizada.

</p>

<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

En contraste, los grupos de mayor edad presentan una menor cantidad de clientes en mora, siendo especialmente reducido el número de casos en los clientes de <b>65 a 69 años</b>. No obstante, esta diferencia puede estar influenciada por una menor cantidad de clientes pertenecientes a dichos rangos de edad, por lo que no constituye evidencia suficiente para concluir que la edad sea un factor determinante del riesgo de mora.

</p>

<p style="
font-size:18px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

En conjunto, el análisis descriptivo no permite identificar un patrón suficientemente marcado que relacione el grupo de edad con el incumplimiento de los clientes. Por ello, se recomienda complementar este estudio mediante análisis estadísticos y modelos predictivos que incorporen variables adicionales, como el nivel de ingreso, la antigüedad laboral, el monto del préstamo y la relación cuota-ingreso, con el fin de identificar los factores que realmente inciden en el riesgo crediticio y fortalecer las estrategias de otorgamiento y seguimiento de préstamos.

</p>




</div>

<div style="
background:#0b1220;
padding:35px;
border:3px solid #3b82f6;
border-radius:15px;
margin:20px 0;
">

<h1 style="
font-size:35px;
color:#3b82f6;
text-align:center;
margin-top:0;
margin-bottom:10px;
">
Conclusiones y Recomendaciones
</h1>

<hr style="border:1px solid #3b82f6; margin-bottom:30px;">

<h3 style="
font-size:22px;
color:#3b82f6;
margin-bottom:10px;
">
Conclusiones
</h3>

<ul style="
font-size:17px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

<li>El banco presenta una tasa de mora del <b>12.7%</b>, equivalente a 127 clientes de una cartera de 1,000. Este nivel de incumplimiento representa un indicador que debe monitorearse de forma continua, especialmente ante un posible crecimiento de la cartera de clientes.</li>

<li>La distribución de los clientes con mora entre los distintos sectores económicos es relativamente homogénea, por lo que el sector laboral no evidencia un comportamiento diferenciador que permita explicar el incumplimiento de pago.</li>

<li>La relación entre el nivel de ingreso y el monto del préstamo no presenta un patrón lineal claramente definido, lo que indica que estas variables, por sí solas, no permiten identificar diferencias evidentes entre clientes con y sin mora.</li>

<li>La antigüedad laboral muestra una distribución similar para ambos grupos de clientes, por lo que tampoco constituye un factor con suficiente capacidad explicativa cuando se analiza de manera individual.</li>

<li>La mayor concentración de clientes en mora se encuentra en los rangos de edad comprendidos entre los <b>20 y 64 años</b>. Sin embargo, el análisis descriptivo no permite concluir que la edad sea un factor determinante del riesgo crediticio, ya que la distribución observada también puede estar influenciada por la composición de la cartera de clientes.</li>

</ul>

<h3 style="
font-size:22px;
color:#3b82f6;
margin-top:35px;
margin-bottom:10px;
">
Recomendaciones
</h3>

<ul style="
font-size:17px;
color:#e0e0e0;
line-height:1.8;
text-align:justify;
">

<li>Complementar el análisis exploratorio mediante técnicas estadísticas y modelos predictivos que permitan identificar los factores con mayor capacidad explicativa sobre la mora y cuantificar su impacto en el riesgo crediticio.</li>

<li>Incorporar variables adicionales relacionadas con el perfil financiero del cliente, como historial de pagos, nivel de endeudamiento, relación cuota-ingreso, comportamiento crediticio previo y calificación de riesgo, con el fin de fortalecer los modelos de evaluación.</li>

<li>Dar seguimiento periódico a la evolución de la tasa de mora mediante indicadores y tableros de control que permitan detectar oportunamente cambios en el comportamiento de la cartera y facilitar la toma de decisiones.</li>

<li>Fortalecer las políticas de otorgamiento y seguimiento de créditos de acuerdo con las normas internas de gestión del riesgo crediticio, priorizando decisiones respaldadas por evidencia estadística y análisis de datos.</li>

</ul>


</div>